### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by BrianHicks** [hoelzro/idea-fight#3]
Hey @hoelzro, I use idea fight literally all the time for everything. Got features to prioritize? Put 'em in idea fight. Want to take up a new hobby? Idea fight. Which Late Night talk show host is the best? You get the idea.

Anyway I want to hit 1 for the left idea and 2 for the right idea (or arrow keys. again, you get the idea). Clicking is _sooo_ 1998.

I'm opening this issue because:
1. Is this something you'd accept?
2. If it's super trivial for you to add, is it worth my time to try and do it?

And thanks for the awesome tool! :heart:

**Comment by hoelzro** [comment]
Hi @BrianHicks!  It makes me really happy to find out that you're enjoying the tool so much!  I think the keyboard idea is fantastic; thanks for checking in advance.  It shouldn't be too hard to implement, but there may need to be a little bit of restructuring of the messages in the Compete module.  If you want to try your hand at making the change, that would be awesome; you can hit me up with any questions.  Otherwise, I could probably do this tomorrow.

**Comment by hoelzro** [comment]
@BrianHicks I just added this tonight; please try it out and let me know what you think!

**Comment by hoelzro** [comment]
@BrianHicks Is it cool if I close this?

**Comment by BrianHicks** [comment]
Not if I do it first!

(Also you totally didn't need my permission 😜)
